# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 13:25
from __future__ import unicode_literals

from django.db import migrations

def create_data(apps, schema_editor):
    User=apps.get_model('tasks', 'Users')
    Status=apps.get_model('tasks', 'Statuses')
    Task=apps.get_model('tasks', 'Tasks')
    u=User(first_name="Иван", last_name="Иванов").save()
    s=Status(title="Новая").save()
    Task(title="Сделать сайт", contractor_id=u, status=s).save()
   

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
